	git rm    Makefile
	git rm    build/Makefile
	git rm    build/sources/dummy.txt
	git rm    pip.txt
	git rm    tests/Dependency.txt
	git rm    tests/ReadMe.txt
	git rm    tests/data_example_01
	git rm    tests/data_example_02
	git rm    tests/data_example_03
	git rm    tests/data_example_04
	git rm    tests/data_example_05
	git rm    tests/data_example_06
	git rm    tests/data_example_07
	git rm    tests/data_example_08
	git rm    tests/data_example_09
	git rm    tests/data_example_10
	git rm    tests/data_example_11
	git rm    tests/data_example_12
	git rm    tests/data_example_13
	git rm    tests/data_example_14
	git rm    tests/data_example_15
	git rm    tests/slow_test_SRWLIB_Example01.py
	git rm    tests/slow_test_SRWLIB_Example01_kick_matr.py
	git rm    tests/slow_test_SRWLIB_Example02.py
	git rm    tests/slow_test_SRWLIB_Example03.py
	git rm    tests/slow_test_SRWLIB_Example04.py
	git rm    tests/slow_test_SRWLIB_Example05.py
	git rm    tests/slow_test_SRWLIB_Example06.py
	git rm    tests/slow_test_SRWLIB_Example06_PETRA.py
	git rm    tests/slow_test_SRWLIB_Example07.py
	git rm    tests/slow_test_SRWLIB_Example08.py
	git rm    tests/slow_test_SRWLIB_Example10.py
	git rm    tests/slow_test_SRWLIB_Example11.py
	git rm    tests/test_SRWLIB_Example09.py
	git rm    tests/test_SRWLIB_Example12.py
	git rm    tests/test_SRWLIB_Example13.py
	git rm    tests/test_SRWLIB_Example14.py
	git rm    tests/test_SRWLIB_Example15.py
	git rm    tests/test_wpg.py

	git add   samples/nanolenses.py
	git add   wpg/__init__.py
	git add   wpg/beamline.py
	git add   wpg/converters/nanolenses/EdfFile.py
	git add   wpg/optical_elements.py

	git rm    wpg/srwl_bl.py
	git rm    wpg/srwl_uti_cryst.py
	git rm    wpg/srwl_uti_src.py
	git rm    wpg/srwl_uti_und.py
	git rm    wpg/srwlib.py
	git rm    wpg/uti_io.py
	git rm    wpg/uti_math.py
	git rm    wpg/uti_plot.py
	git rm    wpg/uti_plot_com.py
	git rm    wpg/uti_plot_matplotlib.py

	git add setup.py
	git add tests/test_null.py
	git add tmp.sh
	git add wpg/srwlib/
